FirstASPWebApp/Models/CalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FirstASPWebApp.Models
{
    public class CalculatorModel
    {
        // should recieve all values from Calculator, and set them against 1-100 parameters
        // send back if the inputs are outside of 1-100 or empty
        
        [Required]
        [Range(0, 100, ErrorMessage = "Asignments must be between 0 and 100")]
        public string asignments { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Quizzes must be between 0 and 100")]
        public string quizzes { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Projects must be between 0 and 100")]
        public string projects { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Intex must be between 0 and 100")]
        public string intex { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Exams must be between 0 and 100")]
        public string exams { get; set; }
        public string extra { get; set; }

    }

}

FirstASPWebApp/Controllers/CalcController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FirstASPWebApp.Models;

namespace FirstASPWebApp.Controllers
{
    public class CalcController : Controller
    {
        public IActionResult Index()
        {
            // throw new IndexOutOfRangeException();      
            return View();
        }

        [HttpGet]
        public IActionResult Calculator()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Calculator( CalculatorModel model)
        {
            return View();
        }
    }
}

FirstASPWebApp/Views/Calc/Calculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade Calculator";
}

@model CalculatorModel;

<!--Calculator should intake all drade values and output total grade-->
<div class="centerIt" id="centerIt">
    <h3>Grade Calculator:</h3>
    <h4>Enter a whole number 1-100 (Example: 90)</h4>
    <form method="post">
        <label>Asignments: </label>
        <input id="asignments" asp-for="asignments"/><br />
        <label>Quizzes: </label>
        <input id="quizzes" asp-for="quizzes"/><br />
        <label>Group Projects: </label>
        <input id="projects" asp-for="projects"/><br />
        <label>INTEX: </label>
        <input id="intex" asp-for="intex"/><br />
        <label>Exams: </label>
        <input id="exams" asp-for="exams"/><br />
        <label>Extra Credit: </label>
        <input id="extra" asp-for="extra" /><br />
        <input id="GradeForm" type="submit" value="Submit" />

        <div asp-validation-summary="All" ></div>
    </form>

    <!-- Output results and final grades here.-->
    <h4>
        Final Letter Grade:
        <r id="finalLetter"> </r>
    </h4>

    <h4 id="finalPercent">
        Final Percentage:
    </h4>
</div>

FirstASPWebApp/Views/Calc/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

    ViewData["Title"] = "Mission 5";

}

<!-- Web page should function as an about me page. It will show a picture, what I ant out of the class, my jobs, and a gradew calculator
    Grade calculator will use a javascript function to calculate my grade based off each
    section of IS 413 class-->

<!--Add name, paragraph of what I want to get out and three jobs-->
<h1> Lucas Gandola</h1>
<img src="img/20220505_180916.jpg" style="width: 200px" />
<h5>
    There's a couple things I want to get out of IS 413. First off, I want to improve my abilities in C#.
    Many of the potential employers I've talked to, seem to want their interns/employees to know it.
    Besides that, I want to learn to learn how to use a program like ASP to more efficiently code in various different languages.
</h5>
<p></p><p></p>

<!--Div class that contains three jobs along with grade calculator-->
<div class="centerIt" id=" centerIt">
    <h3>Top three jobs:</h3>
    <ul>
        <li>1: Web Developer or Software Engineer</li>
        <li>2: Technology Consultant</li>
        <li>3: Something involving Cybersecurity</li>
    </ul>

</div>

FirstASPWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--Page works as a template for all other view pages-->
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <meta charset="utf-8" />
        <title>@ViewData["Title"]</title>
        <link rel="shortcut icon" type="image/jpg" href="img\20210709_184402.jpg" />
        <link href="~/css/default.css" rel="stylesheet" />
        <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    </head>
    <body>


        <nav>
            <a asp-controller="Calc" asp-action="Index">Home</a>
            <a asp-controller="Calc" asp-action="Calculator">Calculator</a>
        </nav>

        <div>
            @RenderBody()
        </div>

        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/lib/jquery/jquery-3.6.3.min.js"></script>
        <script src="~/js/GradeCalculator.js"></script>
    </body>

    <footer>Footer displays down here</footer>
</html>